### ISSUE TITLE
Add Modrinth support

### ISSUE THREAD

**Issue by HerrSammyDE** [mcjars/www#8]
To what extent is it possible add Modrinth?

**Comment by Anthony01M** [comment]
> To what extent is it possible add Modrinth?

Fairly sure Modrinth does not have a server jar itself, unless I couldn't see it, please link me to it

**Comment by HerrSammyDE** [comment]
> > To what extent is it possible add Modrinth?
> 
> Fairly sure Modrinth does not have a server jar itself, unless I couldn't see it, please link me to it

Modrinth has jar files and an API, here:
- https://mohistmc.com/mohistmc-api
- https://mohistmc.com/downloadSoftware?project=mohist&projectVersion=1.20.1

Example:

- https://github.com/pelican-eggs/minecraft/blob/main/java/modrinth/egg-pterodactyl-modrinth-generic.json
![image](https://github.com/user-attachments/assets/0dae65f4-46d7-41f6-a209-1df53b0f99ae)

**Comment by Anthony01M** [comment]
https://mcjars.app/MOHIST/versions

**Comment by HerrSammyDE** [comment]
sorry. i meant Modrinth... I had just checked and Modrinth does not offer Jar files
